name: Android
on: 
  push:
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - "doc/**"
      - "preview/**"
      - ".github/workflows/ios.yml"
      - ".github/workflows/macos.yml"
      - ".github/workflows/ubuntu.yml"
      - ".github/workflows/windows.yml"      
  # pull_request时触发workflow
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - "doc/**"
      - "preview/**"  
      - ".github/workflows/ios.yml"
      - ".github/workflows/macos.yml"
      - ".github/workflows/ubuntu.yml"
      - ".github/workflows/windows.yml"          
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - qt_ver: 5.12.10
            qt_arch: android_x86
          - qt_ver: 5.12.10
            qt_arch: android_armv7
          - qt_ver: 5.12.10
            qt_arch: android_arm64_v8a            
          - qt_ver: 5.15.2
            qt_arch: ''

    steps:
      - name: Install Qt 5.12.10
        if: ${{ matrix.qt_ver }} != '5.15.2'
        uses: jurplel/install-qt-action@v2.10.0
        with:
          # Version of Qt to install
          version: ${{ matrix.qt_ver }}
          # Target platform for build
          target: android
          # Architecture for Windows/Android
          arch: ${{ matrix.qt_arch }}
      - name: Install Qt 5.15.2
        if: ${{ matrix.qt_ver }} == '5.15.2'
        uses: jurplel/install-qt-action@v2.10.0
        with:
          # Version of Qt to install
          version: ${{ matrix.qt_ver }}
          # Target platform for build
          target: android
          # Architecture for Windows/Android
          # arch: ${{ matrix.qt_arch }}          
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build android
        run: |
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
          qmake
          make