name: MacOS
on: 
  # push代码时触发workflow
  push:
    paths:
      - '3rdparty/**'
      - 'examples/**'
      - 'mkspecs/**'
      - 'src/**'
      - '.qmake.conf'
      - 'TaoQuick.pro'
      - '.github/workflows/macos.yml'
  # pull_request时触发workflow
  pull_request:
    paths:
      - '3rdparty/**'
      - 'examples/**'
      - 'mkspecs/**'
      - 'src/**'
      - '.qmake.conf'
      - 'TaoQuick.pro'
      - '.github/workflows/macos.yml'             
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]
        qt_ver: [5.9.9,5.12.10,5.15.2]
        qt_arch: [clang_64]
    env:
      targetName: TaoQuickShow
    steps: 
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.10.0
        with:
          version: ${{ matrix.qt_ver }}
          cached: 'false'
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build macos
        run: |
          qmake
          make
      # tag 打包
      - name: package
        if: startsWith(github.event.ref, 'refs/tags/')
        run: |
          # 拷贝依赖
          macdeployqt bin/release/${targetName}.app -qmldir=. -verbose=1 -dmg

      # tag 上传Release
      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/release/${{ env.targetName }}.dmg
          asset_name: ${{ env.targetName }}-${{ matrix.os }}-${{ matrix.qt_ver }}.dmg
          tag: ${{ github.ref }}
          overwrite: true
